# -*- coding: utf-8 -*-
"""Countdoown.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQH0idQpCd4vererznJSSKx7VTsMDURQ
"""

import time
second = int(input("Ennter seconds for Countdown:"))
for i in range(second,0,-1):
    print(f"Time left : {i} Second(s)",end="\r")
    time.sleep(1)
print("Time is UP!")